#include <cuda_runtime.h>
#include <iostream>
#include <chrono>
#include <cmath>
#include <fstream>
#include <cstdlib>
#include <cstring>

// Forward declarations of CUDA functions
extern "C" {
    void launchGrayscaleKernel(unsigned char* d_input, unsigned char* d_output, 
                              int width, int height);
    void launchGaussianBlurKernel(unsigned char* d_input, unsigned char* d_output, 
                                 int width, int height);
    void launchSharpenKernel(unsigned char* d_input, unsigned char* d_output, 
                            int width, int height);
    void cpuGrayscale(unsigned char* input, unsigned char* output, 
                     int width, int height);
}

void checkCudaError(cudaError_t error, const char* msg) {
    if (error != cudaSuccess) {
        std::cerr << "CUDA Error (" << msg << "): " << cudaGetErrorString(error) << std::endl;
        exit(1);
    }
}

// Generate synthetic test image data
void generateTestImage(unsigned char* data, int width, int height) {
    std::cout << "Generating synthetic test image (" << width << "x" << height << ")..." << std::endl;
    
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            int idx = y * width + x;
            
            // Create interesting patterns: gradients + circular waves
            float fx = (float)x / width;
            float fy = (float)y / height;
            
            // Gradient base
            unsigned char base = (unsigned char)(fx * 255);
            
            // Add circular wave pattern
            float center_x = width / 2.0f;
            float center_y = height / 2.0f;
            float dist = sqrt((x - center_x) * (x - center_x) + (y - center_y) * (y - center_y));
            float wave = sin(dist * 0.1f) * 50 + 50;
            
            // Combine patterns
            int value = (int)(base * 0.7f + wave * 0.3f);
            data[idx] = (unsigned char)(value > 255 ? 255 : (value < 0 ? 0 : value));
        }
    }
}

// Save image in PGM format (simple grayscale format)
bool savePGM(const char* filename, unsigned char* data, int width, int height) {
    std::ofstream file(filename, std::ios::binary);
    if (!file) {
        std::cerr << "Error: Could not create file " << filename << std::endl;
        return false;
    }
    
    // Write PGM header
    file << "P5\n";
    file << "# Generated by CUDA Image Processing\n";
    file << width << " " << height << "\n";
    file << "255\n";
    
    // Write image data
    file.write((char*)data, width * height);
    file.close();
    
    std::cout << "Image saved as PGM: " << filename << std::endl;
    return true;
}

// Calculate basic image statistics
void calculateStats(unsigned char* data, int size, const char* label) {
    long sum = 0;
    int min_val = 255, max_val = 0;
    
    for (int i = 0; i < size; i++) {
        sum += data[i];
        if (data[i] < min_val) min_val = data[i];
        if (data[i] > max_val) max_val = data[i];
    }
    
    double mean = (double)sum / size;
    std::cout << label << " - Mean: " << mean << ", Min: " << min_val << ", Max: " << max_val << std::endl;
}

int main(int argc, char* argv[]) {
    std::cout << "=== CUDA Image Processing Project ===" << std::endl;
    std::cout << "High-performance GPU-accelerated image processing with CUDA" << std::endl;
    std::cout << "Processing pipeline: Grayscale → Gaussian Blur → Sharpening" << std::endl;
    
    // Parse arguments for custom image size
    int width = 512, height = 512;
    if (argc >= 3) {
        width = atoi(argv[1]);
        height = atoi(argv[2]);
        if (width <= 0 || height <= 0 || width > 4096 || height > 4096) {
            std::cerr << "Invalid image dimensions. Using default 512x512." << std::endl;
            width = height = 512;
        }
    }
    
    int imageSize = width * height;
    std::cout << "\nImage dimensions: " << width << "x" << height << " (" << imageSize << " pixels)" << std::endl;
    std::cout << "Memory per image: " << imageSize << " bytes" << std::endl;
    
    // Allocate host memory
    unsigned char* h_input = (unsigned char*)malloc(imageSize);
    unsigned char* h_stage1 = (unsigned char*)malloc(imageSize);  // After grayscale
    unsigned char* h_stage2 = (unsigned char*)malloc(imageSize);  // After blur
    unsigned char* h_output = (unsigned char*)malloc(imageSize);  // After sharpen
    unsigned char* h_cpu_output = (unsigned char*)malloc(imageSize);
    
    // Generate test image
    generateTestImage(h_input, width, height);
    
    // Save input for reference
    savePGM("data/input.pgm", h_input, width, height);
    calculateStats(h_input, imageSize, "Input");
    
    // GPU Processing Pipeline
    std::cout << "\n=== GPU Processing Pipeline ===" << std::endl;
    auto start_gpu = std::chrono::high_resolution_clock::now();
    
    // Allocate device memory
    unsigned char *d_input, *d_temp1, *d_temp2, *d_output;
    checkCudaError(cudaMalloc(&d_input, imageSize), "cudaMalloc d_input");
    checkCudaError(cudaMalloc(&d_temp1, imageSize), "cudaMalloc d_temp1");
    checkCudaError(cudaMalloc(&d_temp2, imageSize), "cudaMalloc d_temp2");
    checkCudaError(cudaMalloc(&d_output, imageSize), "cudaMalloc d_output");
    
    // Copy input data to device
    auto copy_start = std::chrono::high_resolution_clock::now();
    checkCudaError(cudaMemcpy(d_input, h_input, imageSize, cudaMemcpyHostToDevice), 
                   "cudaMemcpy to device");
    auto copy_end = std::chrono::high_resolution_clock::now();
    auto copy_time = std::chrono::duration_cast<std::chrono::microseconds>(copy_end - copy_start).count();
    
    // Stage 1: Grayscale conversion (identity for already gray images)
    auto kernel1_start = std::chrono::high_resolution_clock::now();
    launchGrayscaleKernel(d_input, d_temp1, width, height);
    auto kernel1_end = std::chrono::high_resolution_clock::now();
    auto kernel1_time = std::chrono::duration_cast<std::chrono::microseconds>(kernel1_end - kernel1_start).count();
    
    // Stage 2: Gaussian blur
    auto kernel2_start = std::chrono::high_resolution_clock::now();
    launchGaussianBlurKernel(d_temp1, d_temp2, width, height);
    auto kernel2_end = std::chrono::high_resolution_clock::now();
    auto kernel2_time = std::chrono::duration_cast<std::chrono::microseconds>(kernel2_end - kernel2_start).count();
    
    // Stage 3: Sharpening
    auto kernel3_start = std::chrono::high_resolution_clock::now();
    launchSharpenKernel(d_temp2, d_output, width, height);
    auto kernel3_end = std::chrono::high_resolution_clock::now();
    auto kernel3_time = std::chrono::duration_cast<std::chrono::microseconds>(kernel3_end - kernel3_start).count();
    
    // Copy results back to host
    auto copy_back_start = std::chrono::high_resolution_clock::now();
    checkCudaError(cudaMemcpy(h_stage1, d_temp1, imageSize, cudaMemcpyDeviceToHost), "cudaMemcpy stage1");
    checkCudaError(cudaMemcpy(h_stage2, d_temp2, imageSize, cudaMemcpyDeviceToHost), "cudaMemcpy stage2");
    checkCudaError(cudaMemcpy(h_output, d_output, imageSize, cudaMemcpyDeviceToHost), "cudaMemcpy final");
    auto copy_back_end = std::chrono::high_resolution_clock::now();
    auto copy_back_time = std::chrono::duration_cast<std::chrono::microseconds>(copy_back_end - copy_back_start).count();
    
    auto end_gpu = std::chrono::high_resolution_clock::now();
    auto gpu_total_time = std::chrono::duration_cast<std::chrono::microseconds>(end_gpu - start_gpu).count();
    
    // Free device memory
    cudaFree(d_input);
    cudaFree(d_temp1);
    cudaFree(d_temp2);
    cudaFree(d_output);
    
    // CPU Processing for comparison
    std::cout << "\n=== CPU Processing (Baseline) ===" << std::endl;
    auto start_cpu = std::chrono::high_resolution_clock::now();
    
    cpuGrayscale(h_input, h_cpu_output, width, height);
    
    auto end_cpu = std::chrono::high_resolution_clock::now();
    auto cpu_time = std::chrono::duration_cast<std::chrono::microseconds>(end_cpu - start_cpu).count();
    
    // Performance Analysis
    std::cout << "\n=== Performance Analysis ===" << std::endl;
    std::cout << "GPU Total Time: " << gpu_total_time << " μs" << std::endl;
    std::cout << "  - Host→Device Copy: " << copy_time << " μs" << std::endl;
    std::cout << "  - Grayscale Kernel: " << kernel1_time << " μs" << std::endl;
    std::cout << "  - Gaussian Blur Kernel: " << kernel2_time << " μs" << std::endl;
    std::cout << "  - Sharpening Kernel: " << kernel3_time << " μs" << std::endl;
    std::cout << "  - Device→Host Copy: " << copy_back_time << " μs" << std::endl;
    
    long kernel_total = kernel1_time + kernel2_time + kernel3_time;
    std::cout << "\nCPU Time: " << cpu_time << " μs" << std::endl;
    std::cout << "GPU Kernel Time: " << kernel_total << " μs" << std::endl;
    
    if (cpu_time > 0 && kernel_total > 0) {
        double speedup_total = (double)cpu_time / gpu_total_time;
        double speedup_kernels = (double)cpu_time / kernel_total;
        std::cout << "\nSpeedup (total): " << speedup_total << "x" << std::endl;
        std::cout << "Speedup (kernels only): " << speedup_kernels << "x" << std::endl;
        
        double throughput = (double)imageSize / kernel_total * 1000000.0; // pixels per second
        std::cout << "Throughput: " << throughput / 1000000.0 << " Megapixels/second" << std::endl;
    }
    
    // Verify processing worked
    calculateStats(h_stage1, imageSize, "After Grayscale");
    calculateStats(h_stage2, imageSize, "After Blur");
    calculateStats(h_output, imageSize, "Final Output");
    calculateStats(h_cpu_output, imageSize, "CPU Baseline");
    
    // Save output images
    std::cout << "\n=== Saving Results ===" << std::endl;
    savePGM("data/stage1_grayscale.pgm", h_stage1, width, height);
    savePGM("data/stage2_blurred.pgm", h_stage2, width, height);
    savePGM("data/output_final.pgm", h_output, width, height);
    savePGM("data/cpu_baseline.pgm", h_cpu_output, width, height);
    
    // Data validation
    bool gpu_cpu_match = true;
    int max_diff = 0;
    for (int i = 0; i < imageSize; i++) {
        int diff = abs(h_stage1[i] - h_cpu_output[i]);
        if (diff > max_diff) max_diff = diff;
        if (diff > 1) gpu_cpu_match = false;
    }
    
    std::cout << "\n=== Validation ===" << std::endl;
    std::cout << "GPU vs CPU results match: " << (gpu_cpu_match ? "YES" : "NO") << std::endl;
    std::cout << "Maximum difference: " << max_diff << " (≤1 expected due to rounding)" << std::endl;
    
    // Cleanup
    free(h_input);
    free(h_stage1);
    free(h_stage2);
    free(h_output);
    free(h_cpu_output);
    
    std::cout << "\n=== Processing Complete ===" << std::endl;
    if (cpu_time > 0 && kernel_total > 0) {
        double final_speedup = (double)cpu_time / kernel_total;
        std::cout << "✓ GPU acceleration demonstrated with " << final_speedup << "x speedup" << std::endl;
    } else {
        std::cout << "✓ GPU acceleration demonstrated successfully" << std::endl;
    }
    std::cout << "✓ Multi-stage CUDA pipeline executed successfully" << std::endl;
    std::cout << "✓ Output images saved in PGM format (viewable with GIMP/ImageJ)" << std::endl;
    std::cout << "\nFiles created:" << std::endl;
    std::cout << "  - data/input.pgm (original synthetic image)" << std::endl;
    std::cout << "  - data/stage1_grayscale.pgm (after grayscale conversion)" << std::endl;
    std::cout << "  - data/stage2_blurred.pgm (after Gaussian blur)" << std::endl;
    std::cout << "  - data/output_final.pgm (final sharpened result)" << std::endl;
    std::cout << "  - data/cpu_baseline.pgm (CPU comparison)" << std::endl;
    
    return 0;
} 